import { LexerToken } from '../../../types'
import { keywords } from './keywords'

export const tokens: LexerToken[] = [
  {
    name: 'BEGINCOMMENT',
    test: /^\/\*/,
    enterState: 'COMMENT',
  },
  {
    name: 'NEWLINE',
    test: /^[\n\r]/,
    lineBreaks: true,
    shouldTokenize: lexer => {
      // const nextToken = lexer.peak()

      /*
        If set to true newlines are tokenized.
      */

      // return nextToken && nextToken.name === 'NEWLINE' ? false : true

      return false
    },
  },
  {
    name: 'NULL',
    test: /^null/,
  },
  {
    name: 'NUMBER',
    test: /^[0-9]+(?:\.?[0-9]+)*/,
  },
  {
    name: 'STRING',
    test: /^((?:"(?:[^"\\]|(?:\\.))*")|'(?:[^'\\]|(?:\\.))*')/,
  },
  'INTERFACE',
  'TYPE',
  'THIS',
  'FALSE',
  'TRUE',
  'SWITCH',
  'CASE',
  'DEFAULT',
  'NEW',
  'TRY',
  'CATCH',
  'FINALLY',
  'THROW',
  'DO',
  'WHILE',
  'FUNCTION',
  'RETURN',
  'BREAK',
  'CONTINUE',
  'VOID',
  'AS',
  'FROM',
  'DELETE',
  'CONST',
  'LET',
  'VAR',
  'IF',
  'ELSE',
  'FOR',
  'IN',
  'OF',
  'TYPEOF',
  'INSTANCEOF',
  'IMPORT',
  'EXTENDS',
  'PUBLIC',
  'PROTECTED',
  'PRIVATE',
  'OVERRIDE',
  'ABSCTRACT',
  'GET',
  'SET',
  'IMPLEMENTS',
  'ASSERTS',
  'IS',
  'READONLY',
  'KEYOF',
  'UNIQUE',
  'INFER',
  {
    name: 'IDENTIFIER',
    test: /^[$_\p{ID_Start}]+[$_\p{ID_Continue}]*/u,
    guard: (match: string) => !keywords.includes(match),
  },
  ['SEMI', ';'],
  ['COMMA', ','],
  ['REST', '...'],
  ['DOT', '.'],
  ['DOUBLECOLON', '::'],
  ['COLON', ':'],
  ['PLUSIS', '+='],
  ['MULTIPLY', '*'],
  ['DIVIDE', '/'],
  ['INCREMENT', '++'],
  ['MODULUS', '%'],
  ['PLUS', '+'],
  ['DECREMENT', '--'],
  ['MINUS', '-'],
  ['TENARY', '?'],
  ['ARROW', '=>'],
  ['NOTSTRICTEQUAL', '!=='],
  ['STRICTEQUAL', '==='],
  ['EQUALEQUAL', '=='],
  ['NOTEQUAL', '!='],
  ['LOGNOT', '!'],
  ['EQUAL', '='],
  ['LANGLEBRACKET', '<'],
  ['LTEQ', '<='],
  ['RANGLEBRACKET', '>'],
  ['GTEQ', '>='],
  ['LOGOR', '||'],
  ['XLOGOR', '^'],
  ['LOGAND', '&&'],
  ['BINOR', '|'],
  ['NOT', '~'],
  ['BINAND', '&'],
  ['LPAREN', '('],
  ['RPAREN', ')'],
  ['LCBRACE', '{'],
  ['RCBRACE', '}'],
  ['LBRACK', '['],
  ['RBRACK', ']'],
]
